### ISSUE TITLE
Deduplicate events

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metawatch#5]
Sometimes `fs.watch` sends duplicate events or other processes can generate directory/file events in sequence so we need to add timeout for events deduplication and fire events just once per timeout (like debounce or throttle do).

**Comment by a-kuharenko** [comment]
Hi @tshemsedinov. Could you take a look at my PR(#8) regarding this issue.

**Comment by tshemsedinov** [comment]
Sure, @a-kuharenko will do that in next few days
